"""Añadir campos de celulares a Product

Revision ID: f82fe0f8b6f3
Revises: 6688b6dd36c2
Create Date: 2026-06-13 15:08:53.455798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82fe0f8b6f3'
down_revision = '6688b6dd36c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.alter_column('total_unidades_ch',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imei', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('modelo_celular', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado_celular', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_imei'), ['imei'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_imei'))
        batch_op.drop_column('estado_celular')
        batch_op.drop_column('modelo_celular')
        batch_op.drop_column('marca')
        batch_op.drop_column('imei')

    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.alter_column('total_unidades_ch',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))

    # ### end Alembic commands ###
